/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import rmiservidor.Interfaz;
import rmiservidor.Mensajes;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.net.URL;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;

/**
 *
 * @author arelm
 */
public class VistaChat extends javax.swing.JFrame implements MouseListener, KeyListener {

    String nomUsu;
    Interfaz chat;
    List<Mensajes> Mensj = new ArrayList<>();
    List<String> usuarios = new ArrayList<>();

    public VistaChat (Interfaz chat, String nomUsu) throws RemoteException {
        initComponents();
        this.chat = chat;
        this.nomUsu = nomUsu;
        chat.iniciarses(nomUsu);
        execute();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usuarioslinea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        labelnombre = new javax.swing.JLabel();
        botoncerrarses = new javax.swing.JButton();
        areamensaje = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatarea = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(224, 187, 228));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(224, 187, 228));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Usuarios en línea");

        usuarioslinea.setColumns(20);
        usuarioslinea.setRows(5);
        jScrollPane1.setViewportView(usuarioslinea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 330));

        jPanel3.setBackground(new java.awt.Color(224, 187, 228));

        labelnombre.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        labelnombre.setForeground(new java.awt.Color(102, 0, 102));
        labelnombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelnombre.setText("nom");

        botoncerrarses.setBackground(new java.awt.Color(149, 125, 173));
        botoncerrarses.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        botoncerrarses.setForeground(new java.awt.Color(255, 255, 255));
        botoncerrarses.setText("Cerrar Sesión");
        botoncerrarses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncerrarsesActionPerformed(evt);
            }
        });

        areamensaje.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        areamensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areamensajeActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(149, 125, 173));
        jButton1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        chatarea.setEditable(false);
        chatarea.setContentType("text/html"); // NOI18N
        chatarea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chatarea.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <h1 color='orange'>Equipo: Mario, Areli, Nicole</h1>\n    </p>\n  </body>\n</html>\n");
        jScrollPane2.setViewportView(chatarea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botoncerrarses)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(areamensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(labelnombre))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botoncerrarses, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areamensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 370, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncerrarsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncerrarsesActionPerformed
        try {
            chat.cerrarses(nomUsu);  //use the reference "chat" to call remote methods
            System.exit(0);
            //catch the exceptions may occur, Rubbish URL, RemoteException
        } catch (RemoteException ex) {
            Logger.getLogger(VistaChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botoncerrarsesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        enviarnewmensaje();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void areamensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areamensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areamensajeActionPerformed

    /**
     * @param args the command line arguments
     */
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
          
            }
        });
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areamensaje;
    private javax.swing.JButton botoncerrarses;
    private javax.swing.JTextPane chatarea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelnombre;
    private javax.swing.JTextArea usuarioslinea;
    // End of variables declaration//GEN-END:variables

       private void execute() {
        usuarioslinea.setLineWrap(true);     //para eliminar la barra de desplazamiento horizontal
        setTitle("Chat Público"); 
        addListeners(); 
        this.labelnombre.setText(nomUsu);
        this.setVisible(true);
        setLocationRelativeTo(null);            // para ver la GUI en el medio de la pantalla
        Thread t1 = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    refrescar();                  //este hilo se usa para actualizar la ventana de chat cada segundo
                    try {                       // para mostrar toda la lista de chat
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(VistaChat.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        t1.start();
    }

    public void ListaChat() throws RemoteException {
        chatarea.setText("");
        Mensj = chat.getTodosMens();
        String doc = "<html><body><table>";
        for (Mensajes m : Mensj) {
            if (!((m.getNomUsu().equals(nomUsu)) && (m.getTipo().equals("join")))) {                      
                Date Fecha = m.getFecha();
                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                String a = dateFormat.format(Fecha);
                SimpleDateFormat parseFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                SimpleDateFormat printFormat = new SimpleDateFormat("HH:mm:ss");
                try {
                    Date time = parseFormat.parse(a);
                    doc += "<tr><td>" 
                                + printFormat.format(time) 
                                + "</td><td><font color='rgb(55,178,204)'><b>" 
                                + m.getNomUsu() 
                                + "</b></font></td><td> " 
                                + m.getMensaje() 
                                + "</td></tr>";
                } catch (ParseException ex) {
                    Logger.getLogger(VistaChat.class.getName()).log(Level.SEVERE, null, ex);
                }                        
            }
        }
        doc += "</table></body></html>";
        chatarea.setText(doc);
    }

    private void ListaUsu() throws RemoteException {
        usuarioslinea.setText("");
        usuarios = chat.getTodosUsu();
       // System.out.println(nomUsu + "#$%");
        for (String u : usuarios) {
            if (!u.equals(nomUsu)) {             
                usuarioslinea.append(" " + u + "\n");             
            }
        }
    }

    public void refrescar() {
        try {
            ListaChat();
            ListaUsu();
        } catch (RemoteException ex) {
            Logger.getLogger(VistaChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        Mensajes mensaje = new Mensajes();
        mensaje.setNomUsu(nomUsu);
        mensaje.setTipo("Cliente");
        mensaje.setFecha(new Date());
        try {
            chat.enviarmens(mensaje);
        } catch (RemoteException ex) {
            Logger.getLogger(VistaChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
    
     private void addListeners() {
         areamensaje.addKeyListener(this);
    }

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_ENTER) {
            enviarnewmensaje();
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }

    private void enviarnewmensaje() {
        String EntraMens = areamensaje.getText();
        areamensaje.setText("");
        Mensajes mensaje = new Mensajes();
        mensaje.setNomUsu(nomUsu);
        mensaje.setMensaje(EntraMens);
        mensaje.setTipo("Cliente");
        mensaje.setFecha(new Date());
        try {
            chat.enviarmens(mensaje);
        } catch (RemoteException ex) {
            Logger.getLogger(VistaChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
